### ISSUE TITLE
How to init on server?

### ISSUE THREAD

**Issue by jamesdwilson** [BenjaminRH/meteor-event-hooks#3]
How do you init on the server?
I've tried with an without the startup function.

Thanks again for this really neat package!

Meteor.startup ->
  options =
    updateFocus: 0 
    treatCloseAsLogout: false
  Hooks.init options

W20130819-12:55:02.107(-5)? (STDERR) /home/james/.meteor/tools/4010e5731d/lib/node_modules/fibers/future.js:173
W20130819-12:55:02.108(-5)? (STDERR)                        throw(ex);
W20130819-12:55:02.108(-5)? (STDERR)                              ^
W20130819-12:55:02.113(-5)? (STDERR) TypeError: Object #<Object> has no method 'init'
W20130819-12:55:02.115(-5)? (STDERR)     at server/event-hooks.coffee:17:2
W20130819-12:55:02.115(-5)? (STDERR)     at mains (/home/james/.meteor/tools/4010e5731d/tools/skel-future/.meteor/local/build/programs/server/boot.js:157:61)
W20130819-12:55:02.115(-5)? (STDERR)     at Array.forEach (native)
W20130819-12:55:02.116(-5)? (STDERR)     at Function._.each._.forEach (/home/james/.meteor/tools/4010e5731d/lib/node_modules/underscore/underscore.js:79:11)
W20130819-12:55:02.116(-5)? (STDERR)     at /home/james/.meteor/tools/4010e5731d/tools/skel-future/.meteor/local/build/programs/server/boot.js:157:5

**Comment by BenjaminRH** [comment]
The init method is only defined on the client, you don't have to use it on the server. As the README mentions in the initialization section, the init call should be either in a file on the `client` directory, or inside a `Meteor.isClient`. Cheers!

**Comment by jamesdwilson** [comment]
Yes I saw that, thank you, but then how do I specify options on the server?

James Wilson

**Comment by BenjaminRH** [comment]
Options are only specified on the client, currently. I can see how that could be counter-intuitive :). I've clarified that in the docs.
